const state = {
  fleets:[],
  reports:[],
  transactions:[],
  attendance:[],
  team:[],
  fuels:[],
  payroll:[]
};
const status = (label, type) => `<span class="status ${type}">${label}</span>`;
const internalAuthEmail=id=>`${String(id).trim().toLowerCase()}@accounts.hma.internal`;
document.getElementById('todayButton').textContent=`${new Date().toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'})} ▾`;
const attendanceKey='hma_attendance_records_v2';
const fallbackAttendance=[];
function attendanceRecords(){try{return JSON.parse(localStorage.getItem(attendanceKey))||fallbackAttendance}catch{return fallbackAttendance}}
function workdays(employee,period='2026-08'){return attendanceRecords().filter(x=>x.employee===employee&&x.status==='Hadir'&&x.date.startsWith(period)).length}
function tableRows(items, template, target){const columns={reportRows:6,transactionRows:5,attendanceRows:5,teamRows:6,fuelRows:8,payrollRows:6};const body=document.querySelector(target);body.innerHTML=items.length?items.map(template).join(''):`<tr><td colspan="${columns[body.id]||1}" style="text-align:center;padding:32px;color:#789">Belum ada data operasional.</td></tr>`}
async function loadFuelReports(){if(!window.hmaSupabase)return;const {data,error}=await window.hmaSupabase.from('fuel_logs').select('filled_at,current_odometer,distance_km,expected_liters,liters,vehicles(plate_no),profiles(full_name)').order('filled_at',{ascending:false}).limit(100);if(error||!data?.length)return;state.fuels=data.map(row=>{const expected=Number(row.expected_liters),actual=Number(row.liters),difference=actual-expected,needsValidation=difference>0.5;return [new Date(row.filled_at).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}),row.vehicles?.plate_no||'—',row.profiles?.full_name||'—',Number(row.current_odometer).toLocaleString('id-ID'),`${Number(row.distance_km).toLocaleString('id-ID')} KM`,`${expected.toLocaleString('id-ID',{maximumFractionDigits:2})} L`,`${actual.toLocaleString('id-ID',{maximumFractionDigits:2})} L`,`${difference>=0?'+':''}${difference.toLocaleString('id-ID',{maximumFractionDigits:2})} L`,needsValidation?'Perlu validasi':'Efisien',needsValidation?'pending':'done']});render()}
async function loadTeam(){if(!window.hmaSupabase)return;const {data,error}=await window.hmaSupabase.from('profiles').select('id,employee_code,full_name,position,role').eq('role','employee').order('employee_code');if(error)return;state.team=(data||[]).map(row=>[row.id,row.employee_code||'—',row.full_name,row.position||'Karyawan','Karyawan','Aktif','done']);render()}
function render(){
 document.querySelector('#fleetCards').innerHTML=state.fleets.map(x=>`<article class="fleet-card"><header><div><p>${x[1]}</p><h3>${x[0]}</h3></div>${status(x[3],x[4])}</header><div class="fleet-meta"><span>Driver: <b>${x[2]}</b></span><span>Detail →</span></div></article>`).join('');
 tableRows(state.reports,x=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td><td><b>${x[2]}</b><br><small>${x[3]}</small></td><td><span class="teal-text">${x[4]} berhasil</span><br><small>${x[5]} retur</small></td><td><b>${x[6]}</b><br><small>DFOD ${x[7]}</small></td><td>${status(x[8],x[9])}</td></tr>`,'#reportRows');
 tableRows(state.transactions,x=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td><td class="${x[3]==='Uang Masuk'?'teal-text':'red-text'}">${x[3]}</td><td><b>${x[4]}</b></td><td>${status(x[5],x[6])}</td></tr>`,'#transactionRows');
 tableRows(state.attendance,x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${status(x[3],x[5])}</td><td>${x[4]}</td></tr>`,'#attendanceRows');
 tableRows(state.team,x=>`<tr><td><b>${x[1]}</b></td><td><b>${x[2]}</b></td><td>${x[3]}</td><td>${x[4]}</td><td>${status(x[5],x[6])}</td><td><div class="hero-actions"><button type="button" class="outline-button employee-reset-action" data-id="${x[0]}" data-code="${x[1]}" data-name="${x[2]}">Reset password</button><button type="button" class="outline-button employee-delete-action" data-id="${x[0]}" data-code="${x[1]}" data-name="${x[2]}">Hapus akun</button></div></td></tr>`,'#teamRows');
 tableRows(state.fuels,x=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td><td>${x[2]}</td><td><b>${x[3]}</b></td><td>${x[4]}</td><td>${x[5]} <small>/ ${x[6]}</small></td><td class="${x[7].startsWith('+')?'amber-text':'teal-text'}"><b>${x[7]}</b></td><td>${status(x[8],x[9])}</td></tr>`,'#fuelRows');
 tableRows(state.payroll,x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td><b>${workdays(x[0])} hari</b></td><td><b>${x[2]}</b></td><td>${status(x[3],x[4])}</td><td>${x[4]==='done'?'<button class="outline-button print-slip" data-name="'+x[0]+'">Cetak slip</button>':'—'}</td></tr>`,'#payrollRows');
}
const pageNames={dashboard:['OPERASIONAL','Ringkasan Operasional'],fleets:['OPERASIONAL','Armada'],fuel:['OPERASIONAL','BBM & Perhitungan KM'],reports:['OPERASIONAL','Laporan Karyawan'],transactions:['KEUANGAN','Input Transaksi'],attendance:['HR','Absensi'],payroll:['KEUANGAN','Payroll & Slip Gaji'],team:['PENGATURAN','Tim & Akses']};
document.querySelectorAll('.nav-item[data-view]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.getElementById('sectionEyebrow').textContent=pageNames[id][0];document.getElementById('pageTitle').textContent=pageNames[id][1];document.getElementById('sidebar').classList.remove('open')}));
const modal=document.getElementById('transactionModal'), backdrop=document.getElementById('modalBackdrop');
function closeModal(){modal.close();backdrop.classList.remove('show')}function openModal(){document.getElementById('transactionDate').value=new Date().toISOString().slice(0,10);modal.showModal();backdrop.classList.add('show')}
document.querySelectorAll('[data-open-modal="transaction"]').forEach(x=>x.addEventListener('click',openModal));document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));backdrop.addEventListener('click',closeModal);
document.getElementById('transactionForm').addEventListener('submit',e=>{e.preventDefault();const date=new Date(document.getElementById('transactionDate').value).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'});const type=document.getElementById('transactionType').value==='income'?'Uang Masuk':'Uang Keluar';const amount='Rp '+Number(document.getElementById('transactionAmount').value).toLocaleString('id-ID');state.transactions.unshift([date,document.getElementById('transactionDescription').value,'-',type,amount,'Menunggu','pending']);render();closeModal();const t=document.getElementById('toast');t.textContent='Arus kas dicatat dan menunggu verifikasi.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)});
document.getElementById('menuButton').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
const reportModal=document.getElementById('reportModal');
function closeReportModal(){reportModal.close();backdrop.classList.remove('show')}
function openReportModal(){document.getElementById('reportDate').value=new Date().toISOString().slice(0,10);reportModal.showModal();backdrop.classList.add('show')}
document.querySelectorAll('[data-open-modal="report"]').forEach(x=>x.addEventListener('click',openReportModal));
document.querySelectorAll('[data-close-report]').forEach(x=>x.addEventListener('click',closeReportModal));
document.getElementById('reportForm').addEventListener('submit',e=>{e.preventDefault();const date=new Date(document.getElementById('reportDate').value).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'});const number=`LKR-${Date.now().toString().slice(-6)}`;const currency=id=>'Rp '+Number(document.getElementById(id).value).toLocaleString('id-ID');state.reports.unshift([date,number,document.getElementById('reportDriver').value,document.getElementById('reportRoute').value,document.getElementById('reportSuccess').value,document.getElementById('reportFailed').value,currency('reportCod'),currency('reportDfod'),'Menunggu verifikasi','pending']);render();closeReportModal();const t=document.getElementById('toast');t.textContent='Laporan kerja dikirim untuk verifikasi.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)});
const fuelModal=document.getElementById('fuelModal');
function closeFuelModal(){fuelModal.close();backdrop.classList.remove('show')}
function calculateFuel(){const current=Number(document.getElementById('fuelOdometer').value),previous=Number(document.getElementById('fuelPrevious').value);const label=document.getElementById('fuelEstimate');if(current>previous&&previous>=0){const distance=current-previous;label.textContent=`${distance.toLocaleString('id-ID')} KM · estimasi ${(distance/9).toLocaleString('id-ID',{maximumFractionDigits:2})} L`}else label.textContent='Isi odometer untuk menghitung'}
function openFuelModal(){document.getElementById('fuelDate').value=new Date().toISOString().slice(0,10);fuelModal.showModal();backdrop.classList.add('show')}
document.querySelectorAll('[data-open-modal="fuel"]').forEach(x=>x.addEventListener('click',openFuelModal));document.querySelectorAll('[data-close-fuel]').forEach(x=>x.addEventListener('click',closeFuelModal));
['fuelOdometer','fuelPrevious'].forEach(id=>document.getElementById(id).addEventListener('input',calculateFuel));
document.getElementById('fuelForm').addEventListener('submit',e=>{e.preventDefault();const current=Number(document.getElementById('fuelOdometer').value),previous=Number(document.getElementById('fuelPrevious').value),liters=Number(document.getElementById('fuelLiters').value),distance=current-previous,expected=distance/9,difference=liters-expected,date=new Date(document.getElementById('fuelDate').value).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}),needsValidation=difference>0.5;state.fuels.unshift([date,document.getElementById('fuelVehicle').value,document.getElementById('fuelEmployee').value,current.toLocaleString('id-ID'),`${distance.toLocaleString('id-ID')} KM`,`${expected.toLocaleString('id-ID',{maximumFractionDigits:2})} L`,`${liters.toLocaleString('id-ID',{maximumFractionDigits:2})} L`,`${difference>=0?'+':''}${difference.toLocaleString('id-ID',{maximumFractionDigits:2})} L`,needsValidation?'Perlu validasi':'Efisien',needsValidation?'pending':'done']);render();closeFuelModal();const t=document.getElementById('toast');t.textContent=needsValidation?'Pengisian disimpan dan perlu validasi.':'Pengisian BBM disimpan sebagai efisien.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)});
const fleetModal=document.getElementById('fleetModal');
function closeFleetModal(){fleetModal.close();backdrop.classList.remove('show')}
function openFleetModal(){document.getElementById('fleetForm').reset();document.getElementById('fleetOdometer').value='0';fleetModal.showModal();backdrop.classList.add('show')}
document.querySelectorAll('[data-open-modal="fleet"]').forEach(x=>x.addEventListener('click',openFleetModal));document.querySelectorAll('[data-close-fleet]').forEach(x=>x.addEventListener('click',closeFleetModal));
document.getElementById('fleetForm').addEventListener('submit',async e=>{e.preventDefault();if(!window.hmaSupabase){notify('Koneksi Supabase belum tersedia.');return}const submit=e.currentTarget.querySelector('[type="submit"]');const plate=document.getElementById('fleetPlate').value.trim().toUpperCase().replace(/\s+/g,' ');const model=document.getElementById('fleetModel').value.trim();const statusValue=document.getElementById('fleetStatus').value;const statusInfo={active:['Siap operasi','done'],maintenance:['Dalam perawatan','service'],inactive:['Tidak aktif','service']}[statusValue];if(!await ensureAdminSession()){notify('Masuk sebagai Admin atau HR untuk menyimpan armada.');closeFleetModal();openAdminLogin();return}submit.disabled=true;submit.textContent='Menyimpan…';try{const {error}=await window.hmaSupabase.from('vehicles').insert({plate_no:plate,model,status:statusValue,current_odometer:Number(document.getElementById('fleetOdometer').value)});if(error){if(error.code==='23505')throw new Error('Plat nomor tersebut sudah terdaftar.');throw error}state.fleets.unshift([plate,model,'—',statusInfo[0],statusInfo[1]]);render();closeFleetModal();notify(`Armada ${plate} berhasil disimpan.`)}catch(error){notify(error.message||'Armada belum dapat disimpan.')}finally{submit.disabled=false;submit.textContent='Simpan armada'}});
const fuelTypeModal=document.getElementById('fuelTypeModal'),fuelPriceModal=document.getElementById('fuelPriceModal');
function closeFuelTypeModal(){fuelTypeModal.close();backdrop.classList.remove('show')}function closeFuelPriceModal(){fuelPriceModal.close();backdrop.classList.remove('show')}
async function openFuelMaster(modal,form){if(!await ensureAdminSession()){notify('Masuk sebagai Admin atau HR untuk mengelola master BBM.');openAdminLogin();return}form.reset();modal.showModal();backdrop.classList.add('show')}
document.querySelectorAll('[data-open-modal="fuel-type"]').forEach(x=>x.addEventListener('click',()=>openFuelMaster(fuelTypeModal,document.getElementById('fuelTypeForm'))));
document.querySelectorAll('[data-open-modal="fuel-price"]').forEach(x=>x.addEventListener('click',()=>openFuelMaster(fuelPriceModal,document.getElementById('fuelPriceForm'))));
document.querySelectorAll('[data-close-fuel-type]').forEach(x=>x.addEventListener('click',closeFuelTypeModal));document.querySelectorAll('[data-close-fuel-price]').forEach(x=>x.addEventListener('click',closeFuelPriceModal));
document.getElementById('fuelTypeForm').addEventListener('submit',async e=>{e.preventDefault();const name=document.getElementById('fuelTypeName').value.trim();const {error}=await window.hmaSupabase.from('fuel_types').insert({name});if(error){notify(error.code==='42P01'?'Master BBM belum diaktifkan di server. Jalankan migrasi BBM terlebih dahulu.':error.message);return}document.querySelectorAll('#fuelPriceType,#fuelType').forEach(select=>select.insertAdjacentHTML('beforeend',`<option>${name}</option>`));closeFuelTypeModal();notify('Jenis BBM berhasil ditambahkan.')});
document.getElementById('fuelPriceForm').addEventListener('submit',async e=>{e.preventDefault();const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;try{const vendorName=document.getElementById('fuelVendorName').value.trim(),typeName=document.getElementById('fuelPriceType').value;let {data:vendor,error:vendorError}=await window.hmaSupabase.from('fuel_vendors').upsert({name:vendorName},{onConflict:'name'}).select('id').single();if(vendorError)throw vendorError;const {data:type,error:typeError}=await window.hmaSupabase.from('fuel_types').select('id').eq('name',typeName).single();if(typeError)throw typeError;const {error}=await window.hmaSupabase.from('fuel_prices').insert({vendor_id:vendor.id,fuel_type_id:type.id,price_per_liter:Number(document.getElementById('fuelPriceValue').value)});if(error)throw error;closeFuelPriceModal();notify('Harga BBM dan vendor berhasil disimpan.')}catch(error){notify(error.code==='42P01'?'Master BBM belum diaktifkan di server. Jalankan migrasi BBM terlebih dahulu.':error.message||'Harga BBM belum dapat disimpan.')}finally{submit.disabled=false}});
const salaryModal=document.getElementById('salaryModal');
function closeSalaryModal(){salaryModal.close();backdrop.classList.remove('show')}
function calculateSalary(){const base=Number(document.getElementById('salaryBase').value)||0,allowance=Number(document.getElementById('salaryAllowance').value)||0,deduction=Number(document.getElementById('salaryDeduction').value)||0;document.getElementById('salaryTotal').textContent='Rp '+(base+allowance-deduction).toLocaleString('id-ID')}
function updateSalaryWorkdays(){document.getElementById('salaryWorkdays').value=`${workdays(document.getElementById('salaryEmployee').value)} hari`}
function openSalaryModal(){document.getElementById('salaryPeriod').value=new Date().toLocaleDateString('id-ID',{month:'long',year:'numeric'});updateSalaryWorkdays();calculateSalary();salaryModal.showModal();backdrop.classList.add('show')}
document.querySelectorAll('[data-open-modal="salary"]').forEach(x=>x.addEventListener('click',openSalaryModal));document.querySelectorAll('[data-close-salary]').forEach(x=>x.addEventListener('click',closeSalaryModal));
document.querySelectorAll('[data-action="open-salary"]').forEach(x=>x.addEventListener('click',()=>{document.querySelector('[data-view="payroll"]').click();openSalaryModal()}));
document.querySelectorAll('[data-action="open-employee"]').forEach(x=>x.addEventListener('click',()=>{document.querySelector('[data-view="team"]').click();openEmployeeModal()}));
['salaryBase','salaryAllowance','salaryDeduction'].forEach(id=>document.getElementById(id).addEventListener('input',calculateSalary));
document.getElementById('salaryEmployee').addEventListener('change',updateSalaryWorkdays);
document.getElementById('salaryForm').addEventListener('submit',e=>{e.preventDefault();const base=Number(document.getElementById('salaryBase').value)||0,allowance=Number(document.getElementById('salaryAllowance').value)||0,deduction=Number(document.getElementById('salaryDeduction').value)||0,statusValue=document.getElementById('salaryStatus').value;state.payroll.unshift([document.getElementById('salaryEmployee').value,document.getElementById('salaryPeriod').value,'Rp '+(base+allowance-deduction).toLocaleString('id-ID'),statusValue,statusValue==='Siap dicetak'?'done':'pending']);render();closeSalaryModal();const t=document.getElementById('toast');t.textContent='Gaji karyawan berhasil disimpan.';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)});
const employeeModal=document.getElementById('employeeModal');
function closeEmployeeModal(){employeeModal.close();backdrop.classList.remove('show')}
async function ensureAdminSession(){if(!window.hmaSupabase)return false;const {data:{user},error}=await window.hmaSupabase.auth.getUser();return Boolean(!error&&user)}
async function openEmployeeModal(){if(!await ensureAdminSession()){notify('Silakan masuk sebagai Admin atau HR terlebih dahulu.');openAdminLogin();return}document.getElementById('employeeForm').reset();employeeModal.showModal();backdrop.classList.add('show')}
document.querySelectorAll('[data-open-modal="employee"]').forEach(x=>x.addEventListener('click',openEmployeeModal));
document.querySelectorAll('[data-close-employee]').forEach(x=>x.addEventListener('click',closeEmployeeModal));
document.getElementById('employeeForm').addEventListener('submit',async e=>{e.preventDefault();if(!window.hmaSupabase){notify('Koneksi Supabase belum tersedia.');return}const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Membuat akun…';try{if(!await ensureAdminSession())throw new Error('Sesi Admin/HR tidak ditemukan. Silakan masuk kembali.');const {data:{session}}=await window.hmaSupabase.auth.getSession();if(!session?.access_token)throw new Error('Token sesi tidak ditemukan. Silakan masuk kembali.');const payload={fullName:document.getElementById('employeeName').value,position:document.getElementById('employeePosition').value,baseSalary:Number(document.getElementById('employeeBaseSalary').value),password:document.getElementById('employeePassword').value};const {data,error}=await window.hmaSupabase.functions.invoke('create-employee',{body:payload,headers:{Authorization:`Bearer ${session.access_token}`}});if(error){let detail='Akun belum dapat dibuat.';try{const body=await error.context.json();detail=body.error||detail}catch{}throw new Error(detail)}await loadTeam();closeEmployeeModal();notify(`Akun ${data.employeeCode} berhasil dibuat. Gunakan ID tersebut untuk login.`)}catch(error){notify(error.message||'Akun belum dapat dibuat.')}finally{submit.disabled=false;submit.textContent='Buat akun karyawan'}});
const employeeResetModal=document.getElementById('employeeResetModal');
function closeEmployeeReset(){employeeResetModal.close();backdrop.classList.remove('show')}
function openEmployeeReset(id,code,name){document.getElementById('employeeResetForm').reset();document.getElementById('resetEmployeeId').value=id;document.getElementById('resetEmployeeName').value=`${code} · ${name}`;employeeResetModal.showModal();backdrop.classList.add('show')}
document.querySelectorAll('[data-close-employee-reset]').forEach(button=>button.addEventListener('click',closeEmployeeReset));
async function manageEmployee(body){const {data:{session}}=await window.hmaSupabase.auth.getSession();if(!session?.access_token)throw new Error('Sesi administrator tidak ditemukan.');const {data,error}=await window.hmaSupabase.functions.invoke('manage-employee',{body,headers:{Authorization:`Bearer ${session.access_token}`}});if(error){let detail='Akun belum dapat dikelola.';try{const response=await error.context.json();detail=response.error||detail}catch{}throw new Error(detail)}return data}
document.getElementById('employeeResetForm').addEventListener('submit',async e=>{e.preventDefault();const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;try{const data=await manageEmployee({action:'reset_password',employeeId:document.getElementById('resetEmployeeId').value,password:document.getElementById('resetEmployeePassword').value});closeEmployeeReset();notify(data.message||'Kata sandi berhasil diperbarui.')}catch(error){notify(error.message)}finally{submit.disabled=false}});
document.addEventListener('click',async e=>{const reset=e.target.closest('.employee-reset-action');if(reset){openEmployeeReset(reset.dataset.id,reset.dataset.code,reset.dataset.name);return}const remove=e.target.closest('.employee-delete-action');if(!remove)return;if(!confirm(`Hapus akun ${remove.dataset.code} · ${remove.dataset.name}? Data profil akun akan dihapus permanen.`))return;remove.disabled=true;try{const data=await manageEmployee({action:'delete',employeeId:remove.dataset.id});await loadTeam();notify(data.message||'Akun berhasil dihapus.')}catch(error){notify(error.message)}finally{remove.disabled=false}});
const adminLoginModal=document.getElementById('adminLoginModal');
function closeAdminLogin(){adminLoginModal.close();backdrop.classList.remove('show')}
function openAdminLogin(){adminLoginModal.showModal();backdrop.classList.add('show')}
async function refreshAdminIdentity(){const name=document.getElementById('adminName'),role=document.getElementById('adminRole'),button=document.getElementById('adminSessionButton'),avatar=document.getElementById('adminAvatar');if(!window.hmaSupabase){name.textContent='Admin belum login';role.textContent='Koneksi akun tidak tersedia';button.textContent='Masuk';return}const {data:{user}}=await window.hmaSupabase.auth.getUser();if(!user){name.textContent='Admin belum login';role.textContent='Gunakan akun perusahaan';button.textContent='Masuk';avatar.textContent='AR';return}const {data:profile}=await window.hmaSupabase.from('profiles').select('full_name,role').eq('id',user.id).single();if(profile?.role==='employee'){window.location.replace('employee.html');return}const displayName=profile?.full_name||user.user_metadata?.full_name||user.email;name.textContent=displayName;role.textContent=(profile?.role||'administrator').toUpperCase();avatar.textContent=displayName.split(/\s|@/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'AD';button.textContent='Keluar';}
document.getElementById('adminSessionButton').addEventListener('click',async()=>{if(await ensureAdminSession()){await window.hmaSupabase.auth.signOut();await refreshAdminIdentity();notify('Anda sudah keluar dari akun admin.');return}openAdminLogin()});
document.querySelectorAll('[data-close-admin-login]').forEach(x=>x.addEventListener('click',closeAdminLogin));
document.getElementById('adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();const feedback=document.getElementById('adminLoginFeedback');feedback.hidden=true;if(!window.hmaSupabase){feedback.textContent='Koneksi akun belum tersedia. Muat ulang halaman lalu coba kembali.';feedback.hidden=false;return}const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Memeriksa…';try{const identifier=document.getElementById('adminLoginEmail').value.trim();const email=/^HMA\d{3,}$/i.test(identifier)?internalAuthEmail(identifier):identifier.toLowerCase();const {data,error}=await window.hmaSupabase.auth.signInWithPassword({email,password:document.getElementById('adminLoginPassword').value});if(error||!data.user)throw error||new Error('Sesi login tidak berhasil dibuat.');const {data:profile,error:profileError}=await window.hmaSupabase.from('profiles').select('role').eq('id',data.user.id).single();if(profileError||!profile)throw new Error('Profil akun tidak ditemukan. Hubungi administrator.');if(profile.role==='employee'){window.location.replace('employee.html');return}if(!['admin','hr','finance'].includes(profile.role)){await window.hmaSupabase.auth.signOut();throw new Error('Akun ini tidak memiliki akses aplikasi.');}await refreshAdminIdentity();await loadTeam();closeAdminLogin();notify('Login berhasil.')}catch(error){const message=error?.message==='Invalid login credentials'?'ID/email atau kata sandi tidak sesuai.':(error?.message||'Login gagal.');feedback.textContent=message;feedback.hidden=false;}finally{submit.disabled=false;submit.textContent='Masuk'}});
document.querySelectorAll('[data-password-toggle]').forEach(button=>button.addEventListener('click',()=>{const input=document.getElementById(button.dataset.passwordToggle),shown=input.type==='text';input.type=shown?'password':'text';button.textContent=shown?'◉':'◉̸';button.setAttribute('aria-label',shown?'Tampilkan kata sandi':'Sembunyikan kata sandi')}));
document.getElementById('resetAdminPassword').addEventListener('click',async()=>{const email=document.getElementById('adminLoginEmail').value.trim(),feedback=document.getElementById('adminLoginFeedback');feedback.hidden=true;if(!email||!email.includes('@')){feedback.textContent='Masukkan email administrator. Reset akun karyawan dilakukan dari menu Tim & Akses.';feedback.hidden=false;document.getElementById('adminLoginEmail').focus();return}if(!window.hmaSupabase){feedback.textContent='Koneksi akun belum tersedia.';feedback.hidden=false;return}const {error}=await window.hmaSupabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}${window.location.pathname}`});if(error){feedback.textContent=error.message||'Tautan reset belum dapat dikirim.';feedback.hidden=false;return}feedback.textContent='Tautan pemulihan telah dikirim. Periksa Inbox dan folder Spam.';feedback.style.background='#edf8f7';feedback.style.color='#087c74';feedback.hidden=false});
const passwordRecoveryModal=document.getElementById('passwordRecoveryModal');
function openPasswordRecovery(){passwordRecoveryModal.showModal();backdrop.classList.add('show')}
document.getElementById('passwordRecoveryForm').addEventListener('submit',async e=>{e.preventDefault();const feedback=document.getElementById('passwordRecoveryFeedback'),password=document.getElementById('newPassword').value,confirm=document.getElementById('confirmNewPassword').value;feedback.hidden=true;if(password!==confirm){feedback.textContent='Konfirmasi kata sandi belum sama.';feedback.hidden=false;return}const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;try{const {error}=await window.hmaSupabase.auth.updateUser({password});if(error)throw error;passwordRecoveryModal.close();backdrop.classList.remove('show');notify('Kata sandi berhasil diperbarui. Silakan masuk kembali.')}catch(error){feedback.textContent=error.message||'Kata sandi belum dapat diperbarui.';feedback.hidden=false}finally{submit.disabled=false}});
document.addEventListener('click',e=>{const button=e.target.closest('.print-slip');if(!button)return;const employee=state.payroll.find(x=>x[0]===button.dataset.name);const printWindow=window.open('','_blank');printWindow.document.write(`<title>Slip Gaji ${employee[0]}</title><style>body{font:14px Arial;padding:36px;color:#172a3a}.top{border-bottom:2px solid #148f88;padding-bottom:14px}h1{margin:0}table{width:100%;border-collapse:collapse;margin-top:25px}td{padding:12px;border-bottom:1px solid #ddd}.right{text-align:right}.total{font-weight:bold;font-size:17px}</style><div class="top"><h1>PT HAZARD MAJU ABADI</h1><p>SLIP GAJI KARYAWAN · ${employee[1]}</p></div><table><tr><td>Nama karyawan</td><td class="right">${employee[0]}</td></tr><tr><td>Gaji pokok & tunjangan</td><td class="right">${employee[2]}</td></tr><tr class="total"><td>TOTAL TAKE HOME PAY</td><td class="right">${employee[2]}</td></tr></table><p style="margin-top:60px">Penerima, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Finance / HRD</p>`);printWindow.document.close();printWindow.print()});
function notify(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
const quickRoutes={'Lihat laporan →':'transactions','Semua →':'reports','Lihat semua →':'reports','Kelola armada →':'fleets'};
document.querySelectorAll('button').forEach(button=>{if(button.matches('[data-view],[data-action],[data-open-modal],[data-close-modal],[data-close-report],[data-close-fuel],[data-close-salary],[data-close-employee],[data-close-admin-login]')||button.type==='submit')return;button.addEventListener('click',()=>{const label=button.textContent.trim();if(quickRoutes[label]){document.querySelector(`[data-view="${quickRoutes[label]}"]`).click();return}if(label.includes('Filter')){notify('Filter siap digunakan saat data backend terhubung.');return}if(label.includes('Tinjau payroll')){notify('Payroll periode aktif sedang ditinjau.');return}if(label.includes('Pusat Bantuan')){notify('Pusat bantuan: hubungi administrator operasional.');return}if(label.includes('Tambah armada')||label.includes('Buat periode')){notify('Form ini akan tersedia setelah data master terhubung.');return}if(label==='⋮'||label.includes('Notifikasi')||label.includes('30 Agu')){notify('Tidak ada pembaruan baru.');return}notify('Fitur ini siap dihubungkan ke data operasional.')})});
backdrop.addEventListener('click',()=>{if(reportModal.open)closeReportModal();if(fuelModal.open)closeFuelModal();if(fleetModal.open)closeFleetModal();if(fuelTypeModal.open)closeFuelTypeModal();if(fuelPriceModal.open)closeFuelPriceModal();if(salaryModal.open)closeSalaryModal();if(employeeModal.open)closeEmployeeModal();if(employeeResetModal.open)closeEmployeeReset();if(adminLoginModal.open)closeAdminLogin()});render();refreshAdminIdentity();loadFuelReports();loadTeam();if(window.hmaSupabase)window.hmaSupabase.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')setTimeout(openPasswordRecovery,0);setTimeout(refreshAdminIdentity,0);setTimeout(loadFuelReports,0);setTimeout(loadTeam,0)});setTimeout(async()=>{if(!await ensureAdminSession())openAdminLogin()},0);
