const attendanceKey='hma_attendance_records_v2';
let currentEmployee='';
let currentUser=null;
let currentProfile=null;
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(new Date());
const todayDate=new Date(`${today}T00:00:00`);
document.getElementById('employeeToday').textContent=todayDate.toLocaleDateString('id-ID',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});
document.getElementById('attendanceDay').textContent=String(todayDate.getDate()).padStart(2,'0');
document.getElementById('attendanceMonth').textContent=todayDate.toLocaleDateString('id-ID',{month:'short'}).toUpperCase();
document.getElementById('attendancePeriod').textContent=todayDate.toLocaleDateString('id-ID',{month:'long',year:'numeric'});
const defaultAttendance=[];
let remoteAttendance=[];
let attendanceMode='checkin';
function getAttendance(){const stored=localStorage.getItem(attendanceKey);return stored?JSON.parse(stored):defaultAttendance}
function saveAttendance(records){localStorage.setItem(attendanceKey,JSON.stringify(records))}
function activeAttendance(){return remoteAttendance.length?remoteAttendance:getAttendance().filter(x=>x.employee===currentEmployee)}
function formatTime(value){return value?new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta',hour12:false}).format(new Date(value)):''}
function refreshAttendance(){const records=activeAttendance(),todays=records.find(x=>x.date===today),checkIn=todays&&(todays.checkInTime||todays.time),checkOut=todays&&todays.checkOutTime,complete=Boolean(checkOut);document.getElementById('attendanceCount').textContent=`${records.filter(x=>x.status!=='Tidak hadir').length} hari`;document.getElementById('attendanceHistory').innerHTML=records.slice().reverse().map(x=>{const d=new Date(x.date+'T00:00:00'),timeIn=x.checkInTime||x.time||'—',timeOut=x.checkOutTime||'Belum check-out',location=x.location||x.checkInLocation,coordinate=location?`${Number(location.latitude).toFixed(5)}, ${Number(location.longitude).toFixed(5)}`:'Lokasi tidak tersedia',map=location?`https://www.google.com/maps?q=${location.latitude},${location.longitude}`:'#';return `<article class="history-row">${x.selfie?`<img class="history-selfie" src="${x.selfie}" alt="Selfie absensi">`:`<span class="day">${String(d.getDate()).padStart(2,'0')}<small>${d.toLocaleDateString('id-ID',{month:'short'}).toUpperCase()}</small></span>`}<div><b>Masuk ${timeIn} · Pulang ${timeOut}</b><small>Shift Pagi 08.00–16.00 · ${d.toLocaleDateString('id-ID',{weekday:'long',day:'2-digit',month:'short'})}</small><a class="history-location" href="${map}" target="_blank" rel="noopener">⌖ ${coordinate}</a></div>${status(x.checkOutTime?'Selesai':'Hadir',x.checkOutTime?'active-status':'pending')}</article>`}).join('');const title=!todays?'Belum check-in':complete?'Shift selesai':'Sudah check-in',meta=!todays?'Shift Pagi 08.00–16.00 · selfie dan lokasi diperlukan.':complete?`Masuk ${checkIn} WIB · Pulang ${checkOut} WIB`:`Masuk ${checkIn} WIB · jadwal pulang 16.00 WIB`;document.getElementById('homeAttendanceTitle').textContent=title;document.getElementById('homeAttendanceMeta').textContent=meta;document.getElementById('homeAttendanceIcon').textContent=complete?'✓':todays?'◷':'◷';document.getElementById('homeCheckIn').hidden=complete;document.getElementById('homeCheckIn').textContent=todays?'Check-out sekarang':'Check-in sekarang';document.getElementById('attendanceBoxTitle').textContent=!todays?'Siap untuk check-in':complete?'Absensi lengkap':'Siap check-out';document.getElementById('attendanceBoxMeta').textContent=meta;document.getElementById('attendanceCheckIn').hidden=complete;document.getElementById('attendanceActionLabel').textContent=todays?'Lanjut check-out':'Mulai check-in'}
const attendanceDialog=document.getElementById('attendanceDialog');let cameraStream=null;let capturedLocation=null;let attendanceClock=null;
function deviceTime(){return new Intl.DateTimeFormat('id-ID',{dateStyle:'full',timeStyle:'medium',timeZoneName:'short'}).format(new Date())}
function resetCameraView(){const video=document.getElementById('selfieVideo'),canvas=document.getElementById('selfieCanvas'),placeholder=document.getElementById('cameraPlaceholder');video.hidden=false;canvas.hidden=true;placeholder.hidden=false;document.getElementById('cameraTitle').textContent='Menyiapkan kamera depan';document.getElementById('cameraMessage').textContent='Izinkan kamera agar wajah dapat dipotret.';document.getElementById('takeSelfie').textContent='◉ Ambil selfie';document.getElementById('takeSelfie').disabled=true;document.getElementById('retakeSelfie').hidden=true}
async function startCamera(){const placeholder=document.getElementById('cameraPlaceholder'),video=document.getElementById('selfieVideo');resetCameraView();if(cameraStream)cameraStream.getTracks().forEach(track=>track.stop());if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){document.getElementById('cameraTitle').textContent='Gunakan kamera HP';document.getElementById('cameraMessage').textContent='Kamera live tidak tersedia. Tekan tombol Kamera HP di bawah.';return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:720},height:{ideal:720}},audio:false});video.srcObject=cameraStream;await video.play();placeholder.hidden=true;document.getElementById('takeSelfie').disabled=false}catch(error){document.getElementById('cameraTitle').textContent='Kamera belum diizinkan';document.getElementById('cameraMessage').textContent='Aktifkan izin kamera, atau gunakan tombol Kamera HP.';document.getElementById('takeSelfie').disabled=true}}
function requestLocation(){const statusEl=document.getElementById('locationStatus'),coords=document.getElementById('locationCoordinates'),accuracy=document.getElementById('locationAccuracy');statusEl.textContent='Mencari sinyal GPS…';coords.textContent='Pastikan izin lokasi diaktifkan';accuracy.textContent='…';if(!navigator.geolocation){statusEl.textContent='GPS tidak didukung';coords.textContent='Gunakan perangkat dengan layanan lokasi';accuracy.textContent='—';return}navigator.geolocation.getCurrentPosition(pos=>{capturedLocation={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:Math.round(pos.coords.accuracy)};document.getElementById('locationData').value=JSON.stringify(capturedLocation);statusEl.textContent='Lokasi berhasil dikunci';coords.textContent=`${capturedLocation.latitude.toFixed(6)}, ${capturedLocation.longitude.toFixed(6)}`;accuracy.textContent=`±${capturedLocation.accuracy} m`},error=>{statusEl.textContent='Lokasi belum diizinkan';coords.textContent=error.code===1?'Aktifkan izin lokasi pada browser':'Sinyal GPS belum ditemukan, coba lagi';accuracy.textContent='Gagal'},{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
function updateAttendanceClock(){document.getElementById('trustedTime').textContent=`${deviceTime()} · disahkan saat disimpan`;const now=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()),clock=document.getElementById('shiftClock');if(clock)clock.textContent=`Jam berjalan ${now} WIB · Shift Pagi 08.00–16.00`}
function openAttendance(){if(!currentUser){showToast('Silakan masuk dengan akun karyawan terlebih dahulu.');return}const todays=activeAttendance().find(x=>x.date===today);if(todays?.checkOutTime){showToast('Absensi hari ini sudah lengkap.');return}attendanceMode=todays?'checkout':'checkin';capturedLocation=null;document.getElementById('attendanceForm').reset();document.getElementById('selfieData').value='';document.getElementById('locationData').value='';document.querySelector('#attendanceDialog header p').textContent=attendanceMode==='checkout'?'CHECK-OUT SHIFT PAGI':'CHECK-IN SHIFT PAGI';document.querySelector('#attendanceDialog header h2').textContent=attendanceMode==='checkout'?'Selfie & lokasi check-out':'Selfie & lokasi check-in';document.getElementById('attendanceSubmit').textContent=attendanceMode==='checkout'?'Simpan check-out':'Simpan check-in';attendanceDialog.showModal();updateAttendanceClock();attendanceClock=setInterval(updateAttendanceClock,1000);startCamera();requestLocation()}
function closeAttendance(){attendanceDialog.close();if(attendanceClock){clearInterval(attendanceClock);attendanceClock=null}if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}}
function setCapturedSelfie(dataUrl){document.getElementById('selfieData').value=dataUrl;const canvas=document.getElementById('selfieCanvas'),video=document.getElementById('selfieVideo');canvas.hidden=false;video.hidden=true;document.getElementById('cameraPlaceholder').hidden=true;document.getElementById('takeSelfie').textContent='✓ Selfie siap';document.getElementById('takeSelfie').disabled=true;document.getElementById('retakeSelfie').hidden=false;if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}}
function captureSelfie(){const video=document.getElementById('selfieVideo'),canvas=document.getElementById('selfieCanvas');if(!video.videoWidth){showToast('Kamera belum siap. Gunakan tombol Kamera HP bila perlu.');return}canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);setCapturedSelfie(canvas.toDataURL('image/jpeg',.82))}
function captureSelfieFile(file){if(!file)return;const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{const canvas=document.getElementById('selfieCanvas'),max=960,scale=Math.min(1,max/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);setCapturedSelfie(canvas.toDataURL('image/jpeg',.82))};image.onerror=()=>{URL.revokeObjectURL(url);showToast('Foto tidak dapat dibaca. Silakan ambil ulang.')};image.src=url}
function showToast(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
function dataUrlToBlob(dataUrl){const [meta,raw]=dataUrl.split(',');const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));return new Blob([bytes],{type:meta.match(/:(.*?);/)[1]})}
async function saveAttendanceToSupabase(selfie,location){
  if(!window.hmaSupabase) return false;
  const {data:{user}}=await window.hmaSupabase.auth.getUser();
  if(!user) return false;
  const suffix=crypto.randomUUID();
  const path=`${user.id}/${today}/${attendanceMode}-${suffix}.jpg`;
  const upload=await window.hmaSupabase.storage.from('attendance-selfies').upload(path,dataUrlToBlob(selfie),{contentType:'image/jpeg',upsert:false});
  if(upload.error) throw upload.error;
  const record=attendanceMode==='checkout'?await window.hmaSupabase.rpc('check_out_attendance',{p_latitude:location.latitude,p_longitude:location.longitude,p_accuracy_meters:location.accuracy,p_selfie_path:path,p_client_time:new Date().toISOString()}):await window.hmaSupabase.from('attendance').insert({employee_id:user.id,client_time:new Date().toISOString(),latitude:location.latitude,longitude:location.longitude,accuracy_meters:location.accuracy,selfie_path:path}).select().single();
  if(record.error){await window.hmaSupabase.storage.from('attendance-selfies').remove([path]);throw record.error}
  return record.data||true;
}
async function loadAttendanceFromSupabase(){if(!currentUser||!window.hmaSupabase)return;const {data,error}=await window.hmaSupabase.from('attendance').select('check_in_date,check_in_at,check_out_at,latitude,longitude,accuracy_meters,selfie_path,verification_status').eq('employee_id',currentUser.id).order('check_in_date',{ascending:false});if(error)return;remoteAttendance=(data||[]).map(row=>({employee:currentEmployee,date:row.check_in_date,checkInTime:formatTime(row.check_in_at),checkOutTime:formatTime(row.check_out_at),status:row.check_out_at?'Selesai':'Hadir',checkInLocation:{latitude:row.latitude,longitude:row.longitude,accuracy:row.accuracy_meters},location:{latitude:row.latitude,longitude:row.longitude,accuracy:row.accuracy_meters},synced:true}));refreshAttendance()}
async function saveAttendanceCheckIn(e){e.preventDefault();const selfie=document.getElementById('selfieData').value,location=document.getElementById('locationData').value;if(!selfie||!location){showToast('Selfie dan lokasi GPS wajib dilengkapi.');return}const parsedLocation=JSON.parse(location),mode=attendanceMode,submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Menyimpan…';try{await saveAttendanceToSupabase(selfie,parsedLocation);const records=getAttendance(),now=new Date(),time=now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),existing=records.find(x=>x.employee===currentEmployee&&x.date===today);if(mode==='checkout'&&existing){existing.checkOutTime=time;existing.status='Selesai'}else if(!existing)records.push({employee:currentEmployee,date:today,checkInTime:time,time,status:'Hadir',selfie,location:parsedLocation,deviceTime:deviceTime(),recordedAt:now.toISOString(),synced:true});saveAttendance(records);closeAttendance();await loadAttendanceFromSupabase();refreshAttendance();showToast(mode==='checkout'?'Check-out berhasil tersimpan. Ringkasan kehadiran diperbarui.':'Check-in berhasil tersimpan. Waktu final dicatat server.')}catch(error){showToast(`Absensi belum tersimpan: ${error.message||'coba lagi'}`)}finally{submit.disabled=false;submit.textContent=mode==='checkout'?'Simpan check-out':'Simpan check-in'}}
const tasks=[];
const status=(t,c)=>`<span class="status ${c}">${t}</span>`;
function updateEmployeeGreeting(){const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jakarta',hour:'2-digit',hourCycle:'h23'}).format(new Date())),label=hour<11?'Selamat pagi':hour<15?'Selamat siang':hour<18?'Selamat sore':'Selamat malam',emoji=hour<11?'👋':hour<18?'☀️':'🌙',name=(currentEmployee||'Karyawan').split(' ')[0];document.querySelector('.greeting h1').innerHTML=`${label},<br>${name} <span>${emoji}</span>`;updateAttendanceClock()}
async function applyEmployeeSession(){if(!window.hmaSupabase){showToast('Koneksi backend belum tersedia.');return}const {data:{user}}=await window.hmaSupabase.auth.getUser();if(!user){currentUser=null;currentProfile=null;currentEmployee='';document.body.classList.remove('employee-authenticated');if(!window.location.hash)window.location.replace('./');return}const {data:profile,error}=await window.hmaSupabase.from('profiles').select('employee_code,full_name,role,position').eq('id',user.id).single();if(error||!profile){await window.hmaSupabase.auth.signOut();showToast('Profil karyawan tidak ditemukan. Hubungi administrator.');return}if(profile.role!=='employee'){window.location.replace('./');return}currentUser=user;currentProfile=profile;currentEmployee=profile.full_name;const initials=currentEmployee.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase();document.getElementById('employeeAvatar').textContent=initials||'HM';document.getElementById('employeeProfileName').textContent=currentEmployee;document.getElementById('employeeProfileRole').textContent=`${profile.position||'Karyawan'} · HMA`;document.body.classList.add('employee-authenticated');updateEmployeeGreeting();refreshAttendance();await loadAttendanceFromSupabase();}
document.getElementById('employeeLoginForm').addEventListener('submit',async e=>{e.preventDefault();if(!window.hmaSupabase){showToast('Koneksi backend belum tersedia.');return}const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Memeriksa akun…';try{const employeeId=document.getElementById('employeeLoginId').value.trim().toUpperCase();if(!/^HMA\d{3,}$/.test(employeeId))throw new Error('Format ID karyawan tidak valid. Contoh: HMA001');const {error}=await window.hmaSupabase.auth.signInWithPassword({email:`${employeeId.toLowerCase()}@accounts.hma.internal`,password:document.getElementById('employeeLoginPassword').value});if(error)throw new Error(error.message==='Invalid login credentials'?'ID karyawan atau kata sandi tidak sesuai.':error.message);await applyEmployeeSession();if(!currentUser)throw new Error('Akun ini belum memiliki akses karyawan.');showToast('Login karyawan berhasil.')}catch(error){showToast(error.message||'Login gagal.')}finally{submit.disabled=false;submit.textContent='Masuk ke aplikasi'}});
document.querySelectorAll('[data-password-toggle]').forEach(button=>button.addEventListener('click',()=>{const input=document.getElementById(button.dataset.passwordToggle),shown=input.type==='text';input.type=shown?'password':'text';button.textContent=shown?'◉':'◉̸';button.setAttribute('aria-label',shown?'Tampilkan kata sandi':'Sembunyikan kata sandi')}));
document.getElementById('taskList').innerHTML=tasks.length?tasks.map(x=>`<article class="task-card"><header>${status(x[3],x[4])}<small>${x[0]}</small></header><h2>${x[1]}</h2><p>${x[2]}</p><footer><b>Est. ${x[5]} →</b></footer></article>`).join(''):'<article class="task-card"><h2>Belum ada pekerjaan</h2><p>Tugas dari administrator akan muncul di sini.</p></article>';
document.getElementById('homeCheckIn').addEventListener('click',openAttendance);document.getElementById('attendanceCheckIn').addEventListener('click',openAttendance);document.getElementById('takeSelfie').addEventListener('click',captureSelfie);document.getElementById('selfieFile').addEventListener('change',event=>captureSelfieFile(event.target.files[0]));document.getElementById('retakeSelfie').addEventListener('click',()=>{document.getElementById('selfieData').value='';document.getElementById('selfieFile').value='';startCamera()});document.getElementById('attendanceForm').addEventListener('submit',saveAttendanceCheckIn);document.querySelectorAll('[data-close="attendanceDialog"]').forEach(x=>x.addEventListener('click',closeAttendance));
document.getElementById('takeSelfie').hidden=true;const cameraPicker=document.querySelector('.camera-actions .native-camera');cameraPicker.className='camera-button primary-camera';cameraPicker.childNodes[0].nodeValue='◉ Buka kamera';cameraPicker.querySelector('input').style.display='none';document.querySelector('.camera-actions').style.gridTemplateColumns='1fr';
document.querySelectorAll('[data-screen]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.screen;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'})}));
document.querySelectorAll('[data-back-home]').forEach(button=>button.addEventListener('click',()=>document.querySelector('[data-screen="home"]').click()));
['profile'].forEach(id=>{const screen=document.getElementById(id);if(screen&&!screen.querySelector('[data-back-home]')){const button=document.createElement('button');button.type='button';button.className='pwa-back-button profile-back';button.dataset.backHome='';button.setAttribute('aria-label','Kembali ke beranda');button.textContent='←';button.addEventListener('click',()=>document.querySelector('[data-screen="home"]').click());screen.prepend(button)}});
setInterval(updateEmployeeGreeting,1000);
document.querySelectorAll('.task-filter button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.task-filter button').forEach(x=>x.classList.remove('selected'));button.classList.add('selected')}));
document.querySelectorAll('.notification,.section-heading button:not([data-screen])').forEach(button=>button.addEventListener('click',()=>{const toast=document.getElementById('toast');toast.textContent='Belum ada notifikasi baru.';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}));
const dialog=document.getElementById('reportDialog');let reportEvidenceUrl='';function resetReportEvidence(){if(reportEvidenceUrl)URL.revokeObjectURL(reportEvidenceUrl);reportEvidenceUrl='';const preview=document.getElementById('employeeReportEvidencePreview');preview.hidden=true;preview.removeAttribute('src');document.getElementById('employeeReportEvidenceEmpty').hidden=false;document.getElementById('employeeReportEvidenceBadge').textContent='+ Pilih foto'}function openEmployeeReport(){if(!currentUser){showToast('Silakan masuk dengan akun karyawan terlebih dahulu.');return}document.getElementById('employeeReportForm').reset();resetReportEvidence();document.getElementById('employeeReportDate').value=today;document.getElementById('employeeReportEmployee').textContent=`${currentProfile?.employee_code||'ID Karyawan'} · ${currentEmployee||'Karyawan'}`;dialog.showModal()}document.querySelectorAll('[data-open="report"]').forEach(x=>x.addEventListener('click',openEmployeeReport));document.querySelectorAll('[data-close="reportDialog"]').forEach(x=>x.addEventListener('click',()=>{resetReportEvidence();dialog.close()}));
document.getElementById('employeeReportEvidence').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(!file.type.startsWith('image/')){event.target.value='';showToast('Bukti pekerjaan harus berupa gambar.');return}if(file.size>5*1024*1024){event.target.value='';showToast('Ukuran bukti maksimal 5 MB.');return}if(reportEvidenceUrl)URL.revokeObjectURL(reportEvidenceUrl);reportEvidenceUrl=URL.createObjectURL(file);const preview=document.getElementById('employeeReportEvidencePreview');preview.src=reportEvidenceUrl;preview.hidden=false;document.getElementById('employeeReportEvidenceEmpty').hidden=true;document.getElementById('employeeReportEvidenceBadge').textContent='Ganti foto'});
document.getElementById('employeeReportForm').addEventListener('submit',async e=>{e.preventDefault();if(!currentUser){showToast('Sesi karyawan berakhir. Silakan masuk kembali.');return}const submit=e.currentTarget.querySelector('[type="submit"]'),file=document.getElementById('employeeReportEvidence').files[0];if(!file){showToast('Bukti foto pekerjaan wajib dilampirkan.');return}submit.disabled=true;submit.textContent='Menyimpan…';let evidencePath='';try{const extension=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';evidencePath=`${currentUser.id}/${today}/${crypto.randomUUID()}.${extension}`;const upload=await window.hmaSupabase.storage.from('report-evidence').upload(evidencePath,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;const {error}=await window.hmaSupabase.from('employee_reports').insert({employee_id:currentUser.id,report_date:document.getElementById('employeeReportDate').value,title:'Laporan hasil tugas',description:document.getElementById('employeeReportDescription').value.trim(),success_count:Number(document.getElementById('employeeReportSuccess').value),failed_count:Number(document.getElementById('employeeReportFailed').value),cod_amount:Number(document.getElementById('employeeReportCod').value),dfod_amount:Number(document.getElementById('employeeReportDfod').value),evidence_path:evidencePath});if(error)throw error;resetReportEvidence();dialog.close();showToast('Laporan hasil tugas berhasil dikirim.')}catch(error){if(evidencePath)await window.hmaSupabase.storage.from('report-evidence').remove([evidencePath]);showToast(error.code==='42501'?'Akses laporan belum diaktifkan oleh administrator.':(error.message||'Laporan belum dapat disimpan.'))}finally{submit.disabled=false;submit.textContent='Simpan laporan'}});
const profileDialogs=['profileDataDialog','profileFleetDialog','profileReportsDialog','profileHelpDialog'];
const escapeProfileHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const profileDate=value=>value?new Date(`${String(value).slice(0,10)}T00:00:00`).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}):'—';
function ensureEmployeeSession(){if(currentUser&&currentProfile)return true;showToast('Sesi karyawan berakhir. Silakan masuk kembali.');return false}
function openProfileData(){if(!ensureEmployeeSession())return;const initials=currentProfile.full_name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'HM';document.getElementById('profileDataAvatar').textContent=initials;document.getElementById('profileDataName').textContent=currentProfile.full_name;document.getElementById('profileDataPosition').textContent=`${currentProfile.position||'Karyawan'} · HMA`;document.getElementById('profileDataCode').textContent=currentProfile.employee_code||'Belum tersedia';document.getElementById('profileDataFullName').textContent=currentProfile.full_name;document.getElementById('profileDataJob').textContent=currentProfile.position||'Karyawan';document.getElementById('profileDataDialog').showModal()}
async function openProfileFleet(){if(!ensureEmployeeSession())return;const fleetDialog=document.getElementById('profileFleetDialog'),list=document.getElementById('profileFleetList');list.innerHTML='<div class="profile-loading"><span>◌</span>Memuat riwayat armada…</div>';fleetDialog.showModal();try{const {data,error}=await window.hmaSupabase.from('fuel_logs').select('filled_at,current_odometer,vehicles(id,plate_no,model,status)').eq('employee_id',currentUser.id).order('filled_at',{ascending:false}).limit(50);if(error)throw error;const vehicles=new Map();(data||[]).forEach(row=>{const vehicle=Array.isArray(row.vehicles)?row.vehicles[0]:row.vehicles;if(vehicle&&!vehicles.has(vehicle.id))vehicles.set(vehicle.id,{...vehicle,lastUsed:row.filled_at,odometer:row.current_odometer})});if(!vehicles.size){list.innerHTML='<div class="profile-empty"><span>▱</span>Belum ada armada yang pernah digunakan.<br>Riwayat muncul setelah Anda mengirim pengisian BBM & KM.</div>';return}list.innerHTML=[...vehicles.values()].map(vehicle=>`<article class="profile-fleet-item"><div class="profile-fleet-top"><div><h3>${escapeProfileHtml(vehicle.plate_no)}</h3><p>${escapeProfileHtml(vehicle.model||'Jenis kendaraan belum diisi')}</p></div><span class="profile-status ${vehicle.status==='active'?'reviewed':'submitted'}">${vehicle.status==='active'?'Aktif':'Perawatan'}</span></div><div class="profile-fleet-meta"><span>TERAKHIR DIGUNAKAN<b>${escapeProfileHtml(new Date(vehicle.lastUsed).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}))}</b></span><span>ODOMETER TERAKHIR<b>${Number(vehicle.odometer||0).toLocaleString('id-ID')} KM</b></span></div></article>`).join('')}catch(error){list.innerHTML=`<div class="profile-empty profile-sheet-error"><span>!</span>${escapeProfileHtml(error.message||'Riwayat armada belum dapat dimuat.')}</div>`}}
async function openProfileReports(){if(!ensureEmployeeSession())return;const reportsDialog=document.getElementById('profileReportsDialog'),list=document.getElementById('profileReportList');list.innerHTML='<div class="profile-loading"><span>◌</span>Memuat laporan kerja…</div>';reportsDialog.showModal();try{const {data,error}=await window.hmaSupabase.from('employee_reports').select('id,report_date,title,description,status,success_count,failed_count,cod_amount,dfod_amount').eq('employee_id',currentUser.id).order('report_date',{ascending:false});if(error)throw error;const reports=data||[],reviewed=reports.filter(item=>item.status==='reviewed').length,pending=reports.filter(item=>item.status==='submitted').length;document.getElementById('profileReportTotal').textContent=reports.length;document.getElementById('profileReportReviewed').textContent=reviewed;document.getElementById('profileReportPending').textContent=pending;if(!reports.length){list.innerHTML='<div class="profile-empty"><span>◫</span>Belum ada laporan kerja.<br>Tekan Buat laporan untuk mengirim laporan pertama.</div>';return}const statusLabels={reviewed:'Sudah ditinjau',submitted:'Menunggu',rejected:'Perlu revisi'};list.innerHTML=reports.map(report=>`<article class="profile-report-item"><div class="profile-report-top"><div><h3>Laporan hasil tugas</h3><p>${escapeProfileHtml(profileDate(report.report_date))}</p></div><span class="profile-status ${escapeProfileHtml(report.status)}">${escapeProfileHtml(statusLabels[report.status]||report.status)}</span></div><div class="profile-fleet-meta"><span>SUKSES / GAGAL<b>${Number(report.success_count||0)} / ${Number(report.failed_count||0)}</b></span><span>COD / DFOD<b>Rp ${Number(report.cod_amount||0).toLocaleString('id-ID')} / Rp ${Number(report.dfod_amount||0).toLocaleString('id-ID')}</b></span></div>${report.description?`<p>${escapeProfileHtml(report.description)}</p>`:''}</article>`).join('')}catch(error){document.getElementById('profileReportTotal').textContent='—';document.getElementById('profileReportReviewed').textContent='—';document.getElementById('profileReportPending').textContent='—';list.innerHTML=`<div class="profile-empty profile-sheet-error"><span>!</span>${escapeProfileHtml(error.message||'Laporan kerja belum dapat dimuat.')}</div>`}}
function openProfileHelp(){if(!ensureEmployeeSession())return;document.getElementById('helpEmployeeCode').textContent=currentProfile.employee_code||'Belum tersedia';document.getElementById('profileHelpDialog').showModal()}
document.querySelector('[data-profile-action="data"]').addEventListener('click',openProfileData);document.querySelector('[data-profile-action="fleet"]').addEventListener('click',openProfileFleet);document.querySelector('[data-profile-action="reports"]').addEventListener('click',openProfileReports);document.querySelector('[data-profile-action="help"]').addEventListener('click',openProfileHelp);
document.querySelectorAll('[data-close-profile]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.closeProfile).close()));
document.getElementById('profileCreateReport').addEventListener('click',()=>{document.getElementById('profileReportsDialog').close();openEmployeeReport()});
document.getElementById('helpOpenAttendance').addEventListener('click',()=>{document.getElementById('profileHelpDialog').close();document.querySelector('[data-screen="attendance"]').click()});
document.getElementById('helpOpenReport').addEventListener('click',()=>{document.getElementById('profileHelpDialog').close();openEmployeeReport()});
document.getElementById('copyEmployeeCode').addEventListener('click',async()=>{const code=currentProfile?.employee_code;if(!code){showToast('ID karyawan belum tersedia.');return}try{await navigator.clipboard.writeText(code);showToast('ID karyawan berhasil disalin.')}catch{showToast(`ID karyawan Anda: ${code}`)}});
const fuelDialog=document.getElementById('fuelDialog');
async function openEmployeeFuel(){if(!currentUser){showToast('Silakan masuk dengan akun karyawan terlebih dahulu.');return}const select=document.getElementById('employeeFuelVehicle');select.innerHTML='<option value="">Memuat armada…</option>';document.getElementById('employeeFuelForm').reset();try{const {data,error}=await window.hmaSupabase.from('vehicles').select('id,plate_no,model,current_odometer').in('status',['active','maintenance']).order('plate_no');if(error)throw error;select.innerHTML='<option value="">Pilih kendaraan</option>'+(data||[]).map(vehicle=>`<option value="${vehicle.id}" data-odometer="${vehicle.current_odometer}">${vehicle.plate_no}${vehicle.model?` · ${vehicle.model}`:''}</option>`).join('');if(!(data||[]).length)showToast('Belum ada armada yang dapat dipilih.');fuelDialog.showModal()}catch(error){showToast(error.message||'Daftar armada belum dapat dimuat.')}}
function calculateEmployeeFuel(){const previous=Number(document.getElementById('employeeFuelPrevious').value),current=Number(document.getElementById('employeeFuelCurrent').value),label=document.getElementById('employeeFuelEstimate');if(current>previous){const distance=current-previous;label.textContent=`Jarak ${distance.toLocaleString('id-ID')} KM · estimasi ${(distance/9).toLocaleString('id-ID',{maximumFractionDigits:2})} L`}else label.textContent='Masukkan KM dengan benar untuk melihat estimasi'}
document.querySelectorAll('[data-open="fuel"]').forEach(x=>x.addEventListener('click',openEmployeeFuel));document.querySelectorAll('[data-close="fuelDialog"]').forEach(x=>x.addEventListener('click',()=>fuelDialog.close()));
document.getElementById('employeeFuelVehicle').addEventListener('change',e=>{const option=e.target.selectedOptions[0];if(option?.dataset.odometer)document.getElementById('employeeFuelPrevious').value=option.dataset.odometer;calculateEmployeeFuel()});['employeeFuelPrevious','employeeFuelCurrent'].forEach(id=>document.getElementById(id).addEventListener('input',calculateEmployeeFuel));
document.getElementById('employeeFuelForm').addEventListener('submit',async e=>{e.preventDefault();const submit=e.currentTarget.querySelector('[type="submit"]'),previous=Number(document.getElementById('employeeFuelPrevious').value),current=Number(document.getElementById('employeeFuelCurrent').value);if(current<previous){showToast('KM saat isi harus lebih besar atau sama dengan KM sebelumnya.');return}submit.disabled=true;submit.textContent='Mengirim…';try{const {error}=await window.hmaSupabase.from('fuel_logs').insert({vehicle_id:document.getElementById('employeeFuelVehicle').value,employee_id:currentUser.id,previous_odometer:previous,current_odometer:current,liters:Number(document.getElementById('employeeFuelLiters').value),price_per_liter:Number(document.getElementById('employeeFuelPrice').value),fuel_type:document.getElementById('employeeFuelType').value});if(error)throw error;fuelDialog.close();showToast('Pengisian BBM berhasil dikirim untuk ditinjau admin.')}catch(error){showToast(error.code==='42501'?'Akses input BBM belum diaktifkan oleh administrator.':error.message||'Pengisian BBM belum tersimpan.')}finally{submit.disabled=false;submit.textContent='Kirim pengisian'}});
document.querySelector('.logout').addEventListener('click',async()=>{closeAttendance();profileDialogs.forEach(id=>{const profileDialog=document.getElementById(id);if(profileDialog?.open)profileDialog.close()});if(window.hmaSupabase)await window.hmaSupabase.auth.signOut();currentUser=null;currentProfile=null;currentEmployee='';document.body.classList.remove('employee-authenticated');window.location.replace('./')});
if(window.hmaSupabase)window.hmaSupabase.auth.onAuthStateChange(()=>setTimeout(applyEmployeeSession,0));
applyEmployeeSession();
