const attendanceKey='hma_attendance_records_v2';
let currentEmployee='';
let currentUser=null;
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(new Date());
const todayDate=new Date(`${today}T00:00:00`);
document.getElementById('employeeToday').textContent=todayDate.toLocaleDateString('id-ID',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});
document.getElementById('attendanceDay').textContent=String(todayDate.getDate()).padStart(2,'0');
document.getElementById('attendanceMonth').textContent=todayDate.toLocaleDateString('id-ID',{month:'short'}).toUpperCase();
document.getElementById('attendancePeriod').textContent=todayDate.toLocaleDateString('id-ID',{month:'long',year:'numeric'});
const defaultAttendance=[];
function getAttendance(){const stored=localStorage.getItem(attendanceKey);return stored?JSON.parse(stored):defaultAttendance}
function saveAttendance(records){localStorage.setItem(attendanceKey,JSON.stringify(records))}
function refreshAttendance(){const records=getAttendance().filter(x=>x.employee===currentEmployee);const todays=records.find(x=>x.date===today);document.getElementById('attendanceHistory').innerHTML=records.slice().reverse().map(x=>{const d=new Date(x.date+'T00:00:00');return `<article class="history-row"><span class="day">${String(d.getDate()).padStart(2,'0')}<small>${d.toLocaleDateString('id-ID',{month:'short'}).toUpperCase()}</small></span><div><b>Check-in ${x.time}</b><small>HMA Bekasi</small></div>${status(x.status,x.status==='Hadir'?'active-status':'pending')}</article>`}).join('');const title=todays?'Sudah check-in':'Belum check-in',meta=todays?`${todays.time} WIB · Kantor Bekasi`:'Lakukan absensi untuk mencatat hari kerja.';document.getElementById('homeAttendanceTitle').textContent=title;document.getElementById('homeAttendanceMeta').textContent=meta;document.getElementById('homeAttendanceIcon').textContent=todays?'✓':'◷';document.getElementById('homeCheckIn').hidden=Boolean(todays);document.getElementById('attendanceBoxTitle').textContent=todays?'Check-in berhasil':'Belum check-in';document.getElementById('attendanceBoxMeta').textContent=todays?`${todays.time} WIB · Kantor Bekasi`:'Absensi hari ini belum tercatat';document.getElementById('attendanceCheckIn').hidden=Boolean(todays)}
const attendanceDialog=document.getElementById('attendanceDialog');let cameraStream=null;let capturedLocation=null;
function deviceTime(){return new Intl.DateTimeFormat('id-ID',{dateStyle:'full',timeStyle:'medium',timeZoneName:'short'}).format(new Date())}
async function startCamera(){const placeholder=document.getElementById('cameraPlaceholder');if(!window.isSecureContext||!navigator.mediaDevices){placeholder.querySelector('small').textContent='Kamera hanya aktif melalui localhost atau HTTPS, bukan saat file dibuka langsung.';return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});document.getElementById('selfieVideo').srcObject=cameraStream;placeholder.hidden=true}catch{placeholder.querySelector('small').textContent='Izin kamera ditolak. Aktifkan izin kamera lalu coba lagi.'}}
function requestLocation(){const statusEl=document.getElementById('locationStatus');if(!navigator.geolocation){statusEl.textContent='GPS tidak didukung perangkat ini.';return}navigator.geolocation.getCurrentPosition(pos=>{capturedLocation={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:Math.round(pos.coords.accuracy)};document.getElementById('locationData').value=JSON.stringify(capturedLocation);statusEl.textContent=`GPS terekam · akurasi ±${capturedLocation.accuracy} m`},()=>{statusEl.textContent='Lokasi wajib diizinkan untuk check-in.'},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
function openAttendance(){if(!currentUser){showToast('Silakan masuk dengan akun karyawan terlebih dahulu.');return}const records=getAttendance();if(records.some(x=>x.employee===currentEmployee&&x.date===today))return;capturedLocation=null;document.getElementById('selfieData').value='';document.getElementById('locationData').value='';document.getElementById('trustedTime').textContent=deviceTime();attendanceDialog.showModal();startCamera();requestLocation()}
function closeAttendance(){attendanceDialog.close();if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}}
function captureSelfie(){const video=document.getElementById('selfieVideo'),canvas=document.getElementById('selfieCanvas');if(!video.videoWidth){return}canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);document.getElementById('selfieData').value=canvas.toDataURL('image/jpeg',.78);canvas.hidden=false;video.hidden=true;document.getElementById('takeSelfie').textContent='Selfie berhasil diambil'}
function showToast(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
function dataUrlToBlob(dataUrl){const [meta,raw]=dataUrl.split(',');const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));return new Blob([bytes],{type:meta.match(/:(.*?);/)[1]})}
async function saveAttendanceToSupabase(selfie,location){
  if(!window.hmaSupabase) return false;
  const {data:{user}}=await window.hmaSupabase.auth.getUser();
  if(!user) return false;
  const suffix=crypto.randomUUID();
  const path=`${user.id}/${today}/${suffix}.jpg`;
  const upload=await window.hmaSupabase.storage.from('attendance-selfies').upload(path,dataUrlToBlob(selfie),{contentType:'image/jpeg',upsert:false});
  if(upload.error) throw upload.error;
  const record=await window.hmaSupabase.from('attendance').insert({
    employee_id:user.id,client_time:new Date().toISOString(),latitude:location.latitude,longitude:location.longitude,
    accuracy_meters:location.accuracy,selfie_path:path
  });
  if(record.error){await window.hmaSupabase.storage.from('attendance-selfies').remove([path]);throw record.error}
  return true;
}
async function saveAttendanceCheckIn(e){e.preventDefault();const selfie=document.getElementById('selfieData').value,location=document.getElementById('locationData').value;if(!selfie||!location){showToast('Selfie dan lokasi GPS wajib dilengkapi.');return}const parsedLocation=JSON.parse(location);const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Menyimpan…';try{const synced=await saveAttendanceToSupabase(selfie,parsedLocation);const records=getAttendance(),now=new Date();records.push({employee:currentEmployee,date:today,time:now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),status:'Hadir',selfie,location:parsedLocation,deviceTime:deviceTime(),recordedAt:now.toISOString(),synced});saveAttendance(records);closeAttendance();refreshAttendance();showToast(synced?'Check-in tersimpan aman di server.':'Check-in tersimpan di perangkat. Masuk akun untuk sinkronisasi server.')}catch(error){showToast(`Absensi belum tersimpan: ${error.message||'coba lagi'}`)}finally{submit.disabled=false;submit.textContent='Simpan absensi'}}
const tasks=[];
const status=(t,c)=>`<span class="status ${c}">${t}</span>`;
async function applyEmployeeSession(){if(!window.hmaSupabase){showToast('Koneksi backend belum tersedia.');return}const {data:{user}}=await window.hmaSupabase.auth.getUser();if(!user){currentUser=null;currentEmployee='';document.body.classList.remove('employee-authenticated');if(!window.location.hash)window.location.replace('./');return}const {data:profile,error}=await window.hmaSupabase.from('profiles').select('full_name,role,position').eq('id',user.id).single();if(error||!profile){await window.hmaSupabase.auth.signOut();showToast('Profil karyawan tidak ditemukan. Hubungi administrator.');return}if(profile.role!=='employee'){window.location.replace('./');return}currentUser=user;currentEmployee=profile.full_name;const initials=currentEmployee.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase();document.getElementById('employeeAvatar').textContent=initials||'HM';document.getElementById('employeeProfileName').textContent=currentEmployee;document.getElementById('employeeProfileRole').textContent=`${profile.position||'Karyawan'} · HMA`;document.querySelector('.greeting h1').innerHTML=`Selamat pagi,<br>${currentEmployee.split(' ')[0]} <span>👋</span>`;document.body.classList.add('employee-authenticated');refreshAttendance();}
document.getElementById('employeeLoginForm').addEventListener('submit',async e=>{e.preventDefault();if(!window.hmaSupabase){showToast('Koneksi backend belum tersedia.');return}const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Memeriksa akun…';try{const employeeId=document.getElementById('employeeLoginId').value.trim().toUpperCase();if(!/^HMA\d{3,}$/.test(employeeId))throw new Error('Format ID karyawan tidak valid. Contoh: HMA001');const {error}=await window.hmaSupabase.auth.signInWithPassword({email:`${employeeId.toLowerCase()}@accounts.hma.internal`,password:document.getElementById('employeeLoginPassword').value});if(error)throw new Error(error.message==='Invalid login credentials'?'ID karyawan atau kata sandi tidak sesuai.':error.message);await applyEmployeeSession();if(!currentUser)throw new Error('Akun ini belum memiliki akses karyawan.');showToast('Login karyawan berhasil.')}catch(error){showToast(error.message||'Login gagal.')}finally{submit.disabled=false;submit.textContent='Masuk ke aplikasi'}});
document.querySelectorAll('[data-password-toggle]').forEach(button=>button.addEventListener('click',()=>{const input=document.getElementById(button.dataset.passwordToggle),shown=input.type==='text';input.type=shown?'password':'text';button.textContent=shown?'◉':'◉̸';button.setAttribute('aria-label',shown?'Tampilkan kata sandi':'Sembunyikan kata sandi')}));
document.getElementById('taskList').innerHTML=tasks.length?tasks.map(x=>`<article class="task-card"><header>${status(x[3],x[4])}<small>${x[0]}</small></header><h2>${x[1]}</h2><p>${x[2]}</p><footer><b>Est. ${x[5]} →</b></footer></article>`).join(''):'<article class="task-card"><h2>Belum ada pekerjaan</h2><p>Tugas dari administrator akan muncul di sini.</p></article>';
document.getElementById('homeCheckIn').addEventListener('click',openAttendance);document.getElementById('attendanceCheckIn').addEventListener('click',openAttendance);document.getElementById('takeSelfie').addEventListener('click',captureSelfie);document.getElementById('attendanceForm').addEventListener('submit',saveAttendanceCheckIn);document.querySelectorAll('[data-close="attendanceDialog"]').forEach(x=>x.addEventListener('click',closeAttendance));
document.querySelectorAll('[data-screen]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.screen;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'})}));
document.querySelectorAll('.task-filter button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.task-filter button').forEach(x=>x.classList.remove('selected'));button.classList.add('selected')}));
document.querySelectorAll('.profile-menu button,.notification,.section-heading button:not([data-screen])').forEach(button=>button.addEventListener('click',()=>{const toast=document.getElementById('toast');toast.textContent='Fitur ini siap dihubungkan ke data operasional.';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}));
const dialog=document.getElementById('reportDialog');document.querySelectorAll('[data-open="report"]').forEach(x=>x.addEventListener('click',()=>{if(!currentUser){showToast('Silakan masuk dengan akun karyawan terlebih dahulu.');return}document.getElementById('employeeReportForm').reset();document.getElementById('employeeReportDate').value=today;dialog.showModal()}));document.querySelectorAll('[data-close="reportDialog"]').forEach(x=>x.addEventListener('click',()=>dialog.close()));
document.getElementById('employeeReportForm').addEventListener('submit',async e=>{e.preventDefault();if(!currentUser){showToast('Sesi karyawan berakhir. Silakan masuk kembali.');return}const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Mengirim…';try{const {error}=await window.hmaSupabase.from('employee_reports').insert({employee_id:currentUser.id,report_date:document.getElementById('employeeReportDate').value,title:document.getElementById('employeeReportTitle').value.trim(),description:document.getElementById('employeeReportDescription').value.trim()});if(error)throw error;dialog.close();showToast('Laporan kerja berhasil dikirim untuk ditinjau admin.')}catch(error){showToast(error.code==='42501'?'Akses laporan belum diaktifkan oleh administrator.':(error.message||'Laporan belum dapat dikirim.'))}finally{submit.disabled=false;submit.textContent='Kirim laporan'}});
const fuelDialog=document.getElementById('fuelDialog');
async function openEmployeeFuel(){if(!currentUser){showToast('Silakan masuk dengan akun karyawan terlebih dahulu.');return}const select=document.getElementById('employeeFuelVehicle');select.innerHTML='<option value="">Memuat armada…</option>';document.getElementById('employeeFuelForm').reset();try{const {data,error}=await window.hmaSupabase.from('vehicles').select('id,plate_no,model,current_odometer').in('status',['active','maintenance']).order('plate_no');if(error)throw error;select.innerHTML='<option value="">Pilih kendaraan</option>'+(data||[]).map(vehicle=>`<option value="${vehicle.id}" data-odometer="${vehicle.current_odometer}">${vehicle.plate_no}${vehicle.model?` · ${vehicle.model}`:''}</option>`).join('');if(!(data||[]).length)showToast('Belum ada armada yang dapat dipilih.');fuelDialog.showModal()}catch(error){showToast(error.message||'Daftar armada belum dapat dimuat.')}}
function calculateEmployeeFuel(){const previous=Number(document.getElementById('employeeFuelPrevious').value),current=Number(document.getElementById('employeeFuelCurrent').value),label=document.getElementById('employeeFuelEstimate');if(current>previous){const distance=current-previous;label.textContent=`Jarak ${distance.toLocaleString('id-ID')} KM · estimasi ${(distance/9).toLocaleString('id-ID',{maximumFractionDigits:2})} L`}else label.textContent='Masukkan KM dengan benar untuk melihat estimasi'}
document.querySelectorAll('[data-open="fuel"]').forEach(x=>x.addEventListener('click',openEmployeeFuel));document.querySelectorAll('[data-close="fuelDialog"]').forEach(x=>x.addEventListener('click',()=>fuelDialog.close()));
document.getElementById('employeeFuelVehicle').addEventListener('change',e=>{const option=e.target.selectedOptions[0];if(option?.dataset.odometer)document.getElementById('employeeFuelPrevious').value=option.dataset.odometer;calculateEmployeeFuel()});['employeeFuelPrevious','employeeFuelCurrent'].forEach(id=>document.getElementById(id).addEventListener('input',calculateEmployeeFuel));
document.getElementById('employeeFuelForm').addEventListener('submit',async e=>{e.preventDefault();const submit=e.currentTarget.querySelector('[type="submit"]'),previous=Number(document.getElementById('employeeFuelPrevious').value),current=Number(document.getElementById('employeeFuelCurrent').value);if(current<previous){showToast('KM saat isi harus lebih besar atau sama dengan KM sebelumnya.');return}submit.disabled=true;submit.textContent='Mengirim…';try{const {error}=await window.hmaSupabase.from('fuel_logs').insert({vehicle_id:document.getElementById('employeeFuelVehicle').value,employee_id:currentUser.id,previous_odometer:previous,current_odometer:current,liters:Number(document.getElementById('employeeFuelLiters').value),price_per_liter:Number(document.getElementById('employeeFuelPrice').value),fuel_type:document.getElementById('employeeFuelType').value});if(error)throw error;fuelDialog.close();showToast('Pengisian BBM berhasil dikirim untuk ditinjau admin.')}catch(error){showToast(error.code==='42501'?'Akses input BBM belum diaktifkan oleh administrator.':error.message||'Pengisian BBM belum tersimpan.')}finally{submit.disabled=false;submit.textContent='Kirim pengisian'}});
document.querySelector('.logout').addEventListener('click',async()=>{if(window.hmaSupabase)await window.hmaSupabase.auth.signOut();currentUser=null;currentEmployee='';document.body.classList.remove('employee-authenticated');showToast('Anda sudah keluar dari akun karyawan.')});
if(window.hmaSupabase)window.hmaSupabase.auth.onAuthStateChange(()=>setTimeout(applyEmployeeSession,0));
applyEmployeeSession();
